---
title: "Polynomial-time Mapping Reductions"
description: "Prove that X is as easy as Y"
date: "2025-12-01"
date-format: long
author: Gregory M. Kapfhammer
execute:
  echo: true
format:
  live-revealjs:
    completion: true
    theme: default
    css: ../css/styles.css
    history: false
    scrollable: true
    transition: slide
    highlight-style: github
    footer: "Proofgrammers"
---

# Learning objectives

::: {.fragment .callout-note icon=true title="Learning Objectives for Theoretical Machines"}

- **CS-204-1**: Use both intuitive analysis and theoretical proof
techniques to correctly distinguish between problems that are tractable,
intractable, and uncomputable.
- **CS-204-2**: Correctly use one or more variants of the Turing machine
(TM) abstraction to both describe and analyze the solution to a
computational problem.
- **CS-204-3**: Correctly use one or more variants of the finite state
machine (FSM) abstraction to describe and analyze the solution to a
computational problem.
- **CS-204-4**: Use a formal proof technique to correctly classify a
problem according to whether or not it is in the P, NP, NP-Hard, and/or
NP-Complete complexity class(es).
- **CS-204-5**: Apply insights from theoretical proofs concerning the
limits of either program feasibility or complexity to the implementation
of both correct and efficient real-world Python programs.

:::

## Key insights for proofgrammers

::: {.incremental style="margin-top: -0.25em; font-size: 0.85em;"}

- {{< iconify fa6-solid check-circle >}} **Verifiers**: Formalize "easy
to check" for solutions
- {{< iconify fa6-solid check-circle >}} **PolyCheck**: Problems with
polytime verification
- {{< iconify fa6-solid check-circle >}} **NPoly**: Problems with
nondeterministic polytime solutions
- {{< iconify fa6-solid check-circle >}} **Equivalence**: PolyCheck =
NPoly (remember, this is proven!)
- {{< iconify fa6-solid check-circle >}} **Sandwich**: Poly $\subseteq$
PolyCheck/NPoly $\subseteq$ Expo
- {{< iconify fa6-solid check-circle >}} **P versus NP**: Is Poly $\subset$
PolyCheck/NPoly?

:::

::: {.fragment .fade .boxed-content style="font-size: 0.8em;"}

**Understanding verification unlocks complexity theory**: PolyCheck/NPoly
captures problems where solutions are hard to find but easy to verify. This
class sits between Poly and Expo, leading to the most famous open question
in computer science! We will explore more details soon! Stay tuned!

:::
